spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 10
        min-idle: 0
        max-wait: 1000  #连接池最大的阻塞等待时间
      shutdown-timeout: 2000 #关闭的超时时间
  cache:
    redis:
      time-to-live: -1