server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 0 #最小空闲数
        max-active: 10 #最大连接数
        max-idle: 6 #最大空闲数
    timeout: 2000 #超时时间
