spring:
  data:
    # MongoDB 配置项，对应 MongoProperties 类
    mongodb:
      uri: mongodb://admin:123456@192.168.0.213:27017/iot

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。

